### ISSUE TITLE
How do I give Home Assistant (docker) access to other hardware?

### ISSUE THREAD

**Issue by frankhommers** [dale3h/hassio-installer#13]
I have added an entry to /etc/udev/rules.d/99-usb.rules so that my RFLink gets the name:
/dev/ttyUSB_RFLink

This is on the host. 

How can Home Assistant (set up by this installer) get access to that device?

What actions should I take?

**Comment by dale3h** [comment]
Unfortunately, this is Docker related and beyond my current knowledge of Docker.

@frenck Do you have any knowledge of how this can be achieved?

**Comment by frankhommers** [comment]
I think this is not a problem of your installer. It's a hass.io problem in general ;-)
