### ISSUE TITLE
Hassio CLI

### ISSUE THREAD

**Issue by mickdekkers** [dale3h/hassio-installer#19]
Has anyone gotten the [hassio CLI](https://github.com/home-assistant/hassio-cli) to work?

After running hassio-installer, the hassio CLI doesn't appear to be on the host system or in any of the docker containers.

I've tried manually installing it on the host system like this:

```bash
wget -O hassio https://github.com/home-assistant/hassio-cli/releases/download/1.3.1/hassio_armhf
chmod +x hassio
sudo mv hassio /usr/local/bin/hassio
```

But if I then try to run `hassio ha info` (or any other command that talks to hassio), I get this error:
```
pi@hassio:~ $ hassio ha info
The HTTP request failed with the error: Get http://hassio/homeassistant/info: dial tcp 127.0.1.1:80: getsockopt: connection refused
```
It seems to be trying to talk to hassio through port 80, but that's running on port 8123. I suspect I'm missing some kind of configuration that the hassio image normally takes care of, but I can't find any information in the hassio CLI docs about it.

I can access the web interface just fine, and `ping hassio` and `ping 127.0.1.1` are responding ok.
`curl hassio:8123` and `curl 127.0.1.1:8123` both return the HTML of the web interface.

**Comment by dale3h** [comment]
The `hassio` CLI is not available on the host machine (it is not designed to be). To get access to it, please install the community SSH add-on or the Terminal add-on.

After installing Hass.io, the host SSH connection should be disabled (or at least configured for key-only with) as it is no longer needed.

**Comment by mickdekkers** [comment]
That makes sense, thanks!
