### ISSUE TITLE
Hass.io not not launching after system reboot.

### ISSUE THREAD

**Issue by TheBestMoshe** [dale3h/hassio-installer#3]
I installed hass.io on RPB3+ about a month ago, using this script. It was running fine. Recently I tried logging in to add another device, and the whole thing was glitchy and slow. When clicking on the hass.io page on the Home Assistant instance I got an error. So I just pulled the plug to get it to restart. When I plugged it back in the whole thing was dead. I figured the files were corrupted, so I reflashed the SD card with Raspbian Stretch Lite. I was able to boot up, reinstall hass.io, and install the Samba add-on, however, the Samba server didn't come up on my network. I rebooted from the hass.io menu and Samba share was available. I overwrote the configuration files with backups I had of my original setup and rebooted. The lights just flickered on my Pi, and then it all went dead. Since I was using a 2.1 amp power supply I figured it was an issue with the power. I got a new 2.5 amp official power supply. I reflashed the SD card, reinstalled hass.io, and added the Samba addon. When I restart, Raspbian restarts, but I can't access Home Assistant via the webpage. I have no clue how to check if the Docker containers are running, however, it seems as if hass.io isn't restarting on reboots. I've tried reflashing, rebooting several times, and every time I get the same results.

I'm not sure if this is the right place to post this problem, so if someone can at least point me in the right direction.

**Comment by TheBestMoshe** [comment]
I ran ``` sudo docker ps ``` and this is my results:

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
697a3fb09338        homeassistant/armhf-addon-samba         "/usr/bin/entry.sh /…"   6 hours ago         Up 6 hours                              addon_core_samba
c347c598c586        homeassistant/armhf-hassio-supervisor   "python3 -m hassio"      7 hours ago         Up 6 hours                              hassio_supervisor

```

**Comment by marduv** [comment]
@TheBestMoshe Try running `sudo systemctl enable hassio-supervisor.service`, this will enable hass.io service.
Then you can run `sudo systemctl start hassio-supervisor.service` to start the service.
At last you can run `sudo docker ps` and se if you have an image with name `homeassistant/raspberrypi3-homeassistant`

**Comment by JamesValero** [comment]
I think this would be good if added to the Readme
